### PR TITLE
Update Henry V to follow 1887 Victoria edition

### PR DESCRIPTION
**Pull request by EmmaSweeney**

### CODE REVIEW

**Comment by acabal** [comment]
This is great! However, let's remove the modernize spelling commit. It can change the meter which we don't want. You can just use git rebase to delete that commit, and force push to this pull request. Thanks!

**Comment by EmmaSweeney** [comment]
OK, I've removed that last commit.

**Comment by acabal** [comment]
One more question, in the previous Shakespeare you lowercased titles in the dramatis personae. But in this one, Montjoy is  `Herald` uppercased. Should that be lowercased, as it's a job title?

**Comment by EmmaSweeney** [comment]
The capitalization follows what the Victoria edition. You'll see in Much Ado About Nothing there is "A Boy" and "A Sexton."

**Comment by EmmaSweeney** [comment]
*The capitalization follows the Victoria edition.

**Comment by acabal** [comment]
OK. Let's lowercase this one. I'll lowercase the same in Much Ado. Now that I look, Brother is uppercased once and lowercased once in that one.

**Comment by EmmaSweeney** [comment]
What about "Lords, Ladies, Officers, Soldiers, Citizens, Messengers, and Attendants"? Should this also be changed?

**Comment by acabal** [comment]
Yes, you can lowercase all of those. Thanks!

**Comment by acabal** [comment]
Looks like you re-pushed the modernize spelling commit accidentally?

**Comment by EmmaSweeney** [comment]
Yeah, I messed up. I'm working on it now.

**Comment by EmmaSweeney** [comment]
One day I will figure out how to do this without messing up.

**Comment by acabal** [comment]
On your local repo, do git rebase -i <hash of the commit before the one in this set> 

It should open up in an editor with instructions. I think you can simply delete the line with the modernize-spelling commit, and finish the rebase process and that should be it. Then you can git push -f to your github repo and I think that should update this pull request. Afterwards you can add a new commit with the capitalization stuff.

**Comment by EmmaSweeney** [comment]
One more question, there is "Rambures and Grandpré, French Lords" should lords be lowercased?

**Comment by acabal** [comment]
Yes, I think so

**Comment by EmmaSweeney** [comment]
Done.

**Comment by acabal** [comment]
Awesome, thanks!

**Pull request merged**
